// This file was automatically generated by Vesyla. DO NOT EDIT.

// vesyla_template_start package_head
package _dyqn9udjnhi_pkg;
// vesyla_template_end package_head

  // vesyla_template_start package_macro
  parameter BULK_ADDR_WIDTH = 2;
  parameter BULK_BITWIDTH = 256;
  parameter FSM_PER_SLOT = 4;
  parameter INSTR_OPCODE_BITWIDTH = 3;
  parameter IO_ADDR_WIDTH = 16;
  parameter IO_DATA_WIDTH = 256;
  parameter NUM_SLOTS = 16;
  parameter RESOURCE_INSTR_WIDTH = 27;
  parameter RF_DEPTH = 64;
  parameter WORD_ADDR_WIDTH = 6;
  parameter WORD_BITWIDTH = 16;

  typedef struct packed {
      logic _init_addr_sd;
      logic [15:0] _init_addr;
      logic [1:0] _port;
  } dsu_t;

  function static dsu_t unpack_dsu;
      input logic [23:0] instr;
      dsu_t _dsu;
      _dsu._init_addr_sd = instr[23];
      _dsu._init_addr  = instr[22:7];
      _dsu._port  = instr[6:5];
      return _dsu;
  endfunction

  function static logic [23:0] pack_dsu;
      input dsu_t _dsu;
      logic [23:0] instr;

      instr[23] = _dsu._init_addr_sd;
      instr[22:7] = _dsu._init_addr;
      instr[6:5] = _dsu._port;
      return instr;
  endfunction
  typedef struct packed {
      logic [1:0] _port;
      logic [3:0] _level;
      logic [5:0] _iter;
      logic [5:0] _step;
      logic [5:0] _delay;
  } rep_t;

  function static rep_t unpack_rep;
      input logic [23:0] instr;
      rep_t _rep;
      _rep._port  = instr[23:22];
      _rep._level  = instr[21:18];
      _rep._iter  = instr[17:12];
      _rep._step  = instr[11:6];
      _rep._delay  = instr[5:0];
      return _rep;
  endfunction

  function static logic [23:0] pack_rep;
      input rep_t _rep;
      logic [23:0] instr;

      instr[23:22] = _rep._port;
      instr[21:18] = _rep._level;
      instr[17:12] = _rep._iter;
      instr[11:6] = _rep._step;
      instr[5:0] = _rep._delay;
      return instr;
  endfunction
  typedef struct packed {
      logic [1:0] _port;
      logic [3:0] _level;
      logic [5:0] _iter;
      logic [5:0] _step;
      logic [5:0] _delay;
  } repx_t;

  function static repx_t unpack_repx;
      input logic [23:0] instr;
      repx_t _repx;
      _repx._port  = instr[23:22];
      _repx._level  = instr[21:18];
      _repx._iter  = instr[17:12];
      _repx._step  = instr[11:6];
      _repx._delay  = instr[5:0];
      return _repx;
  endfunction

  function static logic [23:0] pack_repx;
      input repx_t _repx;
      logic [23:0] instr;

      instr[23:22] = _repx._port;
      instr[21:18] = _repx._level;
      instr[17:12] = _repx._iter;
      instr[11:6] = _repx._step;
      instr[5:0] = _repx._delay;
      return instr;
  endfunction
  // vesyla_template_end package_macro

  parameter AGU_BITWIDTH = 16;

endpackage
