// This file was automatically generated by Vesyla. DO NOT EDIT.

// vesyla_template_start package_head
package _pnkjyubmn1c_pkg;
// vesyla_template_end package_head

  // vesyla_template_start package_macro
  parameter BULK_BITWIDTH = 256;
  parameter FSM_PER_SLOT = 4;
  parameter INSTR_OPCODE_BITWIDTH = 3;
  parameter IO_ADDR_WIDTH = 16;
  parameter IO_DATA_WIDTH = 256;
  parameter NUM_SLOTS = 16;
  parameter RESOURCE_INSTR_WIDTH = 27;
  parameter WORD_BITWIDTH = 16;

  typedef struct packed {
      logic [1:0] _option;
      logic [4:0] _mode;
      logic [15:0] _immediate;
  } dpu_t;

  function static dpu_t unpack_dpu;
      input logic [23:0] instr;
      dpu_t _dpu;
      _dpu._option  = instr[23:22];
      _dpu._mode  = instr[21:17];
      _dpu._immediate  = instr[16:1];
      return _dpu;
  endfunction

  function static logic [23:0] pack_dpu;
      input dpu_t _dpu;
      logic [23:0] instr;

      instr[23:22] = _dpu._option;
      instr[21:17] = _dpu._mode;
      instr[16:1] = _dpu._immediate;
      return instr;
  endfunction
  typedef struct packed {
      logic [1:0] _port;
      logic [3:0] _level;
      logic [5:0] _iter;
      logic [5:0] _step;
      logic [5:0] _delay;
  } rep_t;

  function static rep_t unpack_rep;
      input logic [23:0] instr;
      rep_t _rep;
      _rep._port  = instr[23:22];
      _rep._level  = instr[21:18];
      _rep._iter  = instr[17:12];
      _rep._step  = instr[11:6];
      _rep._delay  = instr[5:0];
      return _rep;
  endfunction

  function static logic [23:0] pack_rep;
      input rep_t _rep;
      logic [23:0] instr;

      instr[23:22] = _rep._port;
      instr[21:18] = _rep._level;
      instr[17:12] = _rep._iter;
      instr[11:6] = _rep._step;
      instr[5:0] = _rep._delay;
      return instr;
  endfunction
  typedef struct packed {
      logic [1:0] _port;
      logic [3:0] _level;
      logic [5:0] _iter;
      logic [5:0] _step;
      logic [5:0] _delay;
  } repx_t;

  function static repx_t unpack_repx;
      input logic [23:0] instr;
      repx_t _repx;
      _repx._port  = instr[23:22];
      _repx._level  = instr[21:18];
      _repx._iter  = instr[17:12];
      _repx._step  = instr[11:6];
      _repx._delay  = instr[5:0];
      return _repx;
  endfunction

  function static logic [23:0] pack_repx;
      input repx_t _repx;
      logic [23:0] instr;

      instr[23:22] = _repx._port;
      instr[21:18] = _repx._level;
      instr[17:12] = _repx._iter;
      instr[11:6] = _repx._step;
      instr[5:0] = _repx._delay;
      return instr;
  endfunction
  typedef struct packed {
      logic [1:0] _port;
      logic [6:0] _delay_0;
      logic [6:0] _delay_1;
      logic [6:0] _delay_2;
  } fsm_t;

  function static fsm_t unpack_fsm;
      input logic [23:0] instr;
      fsm_t _fsm;
      _fsm._port  = instr[23:22];
      _fsm._delay_0  = instr[21:15];
      _fsm._delay_1  = instr[14:8];
      _fsm._delay_2  = instr[7:1];
      return _fsm;
  endfunction

  function static logic [23:0] pack_fsm;
      input fsm_t _fsm;
      logic [23:0] instr;

      instr[23:22] = _fsm._port;
      instr[21:15] = _fsm._delay_0;
      instr[14:8] = _fsm._delay_1;
      instr[7:1] = _fsm._delay_2;
      return instr;
  endfunction
  // vesyla_template_end package_macro

  parameter FSM_MAX_STATES = 4;
  parameter FSM_DELAY_WIDTH = 3;
  parameter DPU_MODE_WIDTH = 6;
  parameter DPU_IMMEDIATE_WIDTH = 8;
  parameter OPCODE_WIDTH = 4;
  parameter BITWIDTH = 16;
  parameter INSTRUCTION_PAYLOAD_WIDTH = 27;
  parameter OPCODE_H = 26;
  parameter OPCODE_L = 24;
  parameter OPCODE_DPU = 3;
  parameter OPCODE_FSM = 2;
  parameter DPU_MODE_ADD = 1;
  parameter DPU_MODE_MUL = 7;
  parameter DPU_MODE_MAC = 10;

endpackage
